<a href="https://colab.research.google.com/github/ManoharKonala/BootCamp_2K24/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/ManoharKonala/BootCamp_2K24.git

Cloning into 'BootCamp_2K24'...
remote: Enumerating objects: 242, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 242 (delta 79), reused 58 (delta 26), pack-reused 109
Receiving objects: 100% (242/242), 318.07 KiB | 6.12 MiB/s, done.
Resolving deltas: 100% (115/115), done.


#NUMPY
* NumPy stands for Numerical Python and is a core library for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.

* Mathematical algorithms implemented in interpreted languages, for example, Python, often work much slower than the same algorithms implemented in compiled languages (for example, Fortran, C, and Java). The NumPy library provides implementations of computational algorithms in the form of functions and operators, optimized for working with multidimensional arrays. As a result, any algorithm that can be expressed as a sequence of operations on arrays (matrices) and implemented using NumPy works as fast as the equivalent code executed in MATLAB. If we compare numpy vs math, we quickly find thatnumpy has more advantages for computation methods compared to math.

#NumPy Vs List

**When to use NumPy:**

* When you need high performance and efficiency for large datasets.
* When performing complex mathematical operations and numerical computations.
* When working with multidimensional data and matrices.

**When to use Python lists:**

* When you need a general-purpose, flexible data structure.
* When your dataset is relatively small and performance is not a critical issue.
* When you need to store mixed data types or perform operations that NumPy doesn't directly support.

# INSTALLING NUMPY
* You can install NumPy using the Python package installer pip:

In [ ]:
pip install numpy

* To verify your numpy version


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


# NumPy Arrays
* The central feature of NumPy is its array object, **ndarray**. These arrays are more efficient and flexible than Python lists. Here's how you can create and manipulate them.
* Unlike sequences in Python, arrays in NumPy have a fixed size, the elements of the array must be of the same type.

**Array**
* An array in NumPy is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

**2D Array**
* A 2D array (matrix) in NumPy is an array of arrays. It can be thought of as a table of values, with rows and columns.

**3D Array**
* A 3D array in NumPy is an array of 2D arrays (a collection of matrices). It can be visualized as a cube of values.


* **1D Array:** A simple list of elements.
* **2D Array:** A table of elements, with rows and columns.
* **3D Array:** A cube of elements, with depth, rows, and columns.

In [ ]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)


[1 2 3 4 5]


In [ ]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Creating a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]],
                     [[13, 14, 15], [16, 17, 18]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


# Numpy Attributes
a.ndim  ==> Number of dimensions

b.shape ==> Shape of the array

a.size  ==> Total number of elements

a.dtype ==> Data type of the elements

In [ ]:
# Creating an array from a list
a = np.array([1, 2, 3, 4])

# Creating a 2D array (matrix)
b = np.array([[1, 2], [3, 4]])


print(a.ndim)
print(b.shape)
print(a.size)
print(a.dtype)

1
(2, 2)
4
int64


In [2]:
import numpy as np
# Integer array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

# Float array
b = np.array([1.0, 2.0, 3.0])
print(b.dtype)

# Complex array
c = np.array([1+2j, 3+4j])
print(c.dtype)

# Boolean array
d = np.array([True, False, True])
print(d.dtype)

int64
float64
complex128
bool


In [6]:
# Create an array with float32 data type
a = np.array([1, 2, 3], dtype=np.float32)
print(a)
print(a.dtype)


[1. 2. 3.]
float32


In [5]:
# Create an array with int16 data type
b = np.array([1, 2, 3], dtype=np.int16)
print(b)
print(b.dtype)

[1 2 3]
int16


In [8]:
c = np.array([1+2j, 3+4j], dtype=np.int16)
print(c)
print(c.dtype)   # This will raise a TypeError

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

# Built-In Functions

* np.array(): Create an array from a Python list or sequence.


In [9]:
# From a list
A = np.array([11, 22, 33, 44, 55])
print(A)

[11 22 33 44 55]


In [10]:
# From a sequence
B = np.array((100, 200, 300))
print(B)

[100 200 300]


* np.asarray(): Convert the input to an array.
