<a href="https://colab.research.google.com/github/ManoharKonala/BootCamp_2K24/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/ManoharKonala/BootCamp_2K24.git

Cloning into 'BootCamp_2K24'...
remote: Enumerating objects: 242, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 242 (delta 79), reused 58 (delta 26), pack-reused 109
Receiving objects: 100% (242/242), 318.07 KiB | 6.12 MiB/s, done.
Resolving deltas: 100% (115/115), done.


#NUMPY
* NumPy stands for Numerical Python and is a core library for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.

* Mathematical algorithms implemented in interpreted languages, for example, Python, often work much slower than the same algorithms implemented in compiled languages (for example, Fortran, C, and Java). The NumPy library provides implementations of computational algorithms in the form of functions and operators, optimized for working with multidimensional arrays. As a result, any algorithm that can be expressed as a sequence of operations on arrays (matrices) and implemented using NumPy works as fast as the equivalent code executed in MATLAB. If we compare numpy vs math, we quickly find thatnumpy has more advantages for computation methods compared to math.

#NumPy Vs List

**When to use NumPy:**

* When you need high performance and efficiency for large datasets.
* When performing complex mathematical operations and numerical computations.
* When working with multidimensional data and matrices.

**When to use Python lists:**

* When you need a general-purpose, flexible data structure.
* When your dataset is relatively small and performance is not a critical issue.
* When you need to store mixed data types or perform operations that NumPy doesn't directly support.

# INSTALLING NUMPY
* You can install NumPy using the Python package installer pip:

In [ ]:
pip install numpy

* To verify your numpy version


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


# NumPy Arrays
* The central feature of NumPy is its array object, **ndarray**. These arrays are more efficient and flexible than Python lists. Here's how you can create and manipulate them.
* Unlike sequences in Python, arrays in NumPy have a fixed size, the elements of the array must be of the same type.

**Array**
* An array in NumPy is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

**2D Array**
* A 2D array (matrix) in NumPy is an array of arrays. It can be thought of as a table of values, with rows and columns.

**3D Array**
* A 3D array in NumPy is an array of 2D arrays (a collection of matrices). It can be visualized as a cube of values.


* **1D Array:** A simple list of elements.
* **2D Array:** A table of elements, with rows and columns.
* **3D Array:** A cube of elements, with depth, rows, and columns.

In [ ]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)


[1 2 3 4 5]


In [ ]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Creating a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]],
                     [[13, 14, 15], [16, 17, 18]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


# Numpy Attributes
a.ndim  ==> Number of dimensions

b.shape ==> Shape of the array

a.size  ==> Total number of elements

a.dtype ==> Data type of the elements

In [ ]:
# Creating an array from a list
a = np.array([1, 2, 3, 4])

# Creating a 2D array (matrix)
b = np.array([[1, 2], [3, 4]])


print(a.ndim)
print(b.shape)
print(a.size)
print(a.dtype)

1
(2, 2)
4
int64


In [ ]:
import numpy as np
# Integer array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

# Float array
b = np.array([1.0, 2.0, 3.0])
print(b.dtype)

# Complex array
c = np.array([1+2j, 3+4j])
print(c.dtype)

# Boolean array
d = np.array([True, False, True])
print(d.dtype)

int64
float64
complex128
bool


In [ ]:
# Create an array with float32 data type
a = np.array([1, 2, 3], dtype=np.float32)
print(a)
print(a.dtype)


[1. 2. 3.]
float32


In [ ]:
# Create an array with int16 data type
b = np.array([1, 2, 3], dtype=np.int16)
print(b)
print(b.dtype)

[1 2 3]
int16


In [ ]:
c = np.array([1+2j, 3+4j], dtype=np.int16)
print(c)
print(c.dtype)   # This will raise a TypeError

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

# Built-In Functions

* np.array(): Create an array from a Python list or sequence.


In [ ]:
# From a list
A = np.array([11, 22, 33, 44, 55])
print(A)

[11 22 33 44 55]


In [ ]:
# From a sequence
B = np.array((100, 200, 300))
print(B)

[100 200 300]


* np.asarray(): Convert the input to an array.


In [ ]:
import numpy as np
t = [1,2,3,4,5,6]
a = np.asarray(t)
print(a)

[1 2 3 4 5 6]


In [ ]:
# from a tuple
f = (1,2,3)
a = np.asarray(f)
print(a)

[1 2 3]


* np.ones(shape): Creates an array filled with ones.

In [ ]:
# Create an 2D array of ones
ones = np.ones((2, 4))
print("Array of ones:\n", ones)

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* np.zeros(shape): Creates an array filled with zeros.

In [ ]:
# Create an 2D array of zeros
zeros = np.zeros((3, 3))
print("Array of zeros:\n", zeros)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* np.empty(): Create an uninitialized array.

In [ ]:
# Create an uninitialized 1D array
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


* np.arange(start, stop, step): Creates an array with a range of values.

In [ ]:
# Create an array with a range of values
range_arr = np.arange(0, 10, 2)
print("Range array:", range_arr)

Range array: [0 2 4 6 8]


* np.linspace(start, stop, num): Creates an array with num equally spaced values between start and stop.

In [ ]:
# Create an array with linearly spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

Linspace array: [0.   0.25 0.5  0.75 1.  ]


* np.eye(n): Creates an identity matrix of size n x n.

In [ ]:
# Create an identity matrix
identity = np.eye(4)
print("Identity matrix:\n", identity)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* np.full(shape, value): Creates an array filled with the given value.

In [ ]:
# Create a full array
full = np.full((2, 2), 7)
print("Full array:\n", full)

Full array:
 [[7 7]
 [7 7]]


# Numpy Array Operations and Broadcasting

**Basic Array Operations**
* NumPy allows for element-wise and matrix operations.

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)    # Addition
print(x - y)    # Subtraction
print(x * y)    # Multiplication
print(x / y)    # Division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Scalar Operations: Multiplies/Divides each element of the array by the scalar value;
a = np.array([1, 2, 3])

b = a * 2
print(b)

c = a / 2
print(c)

[2 4 6]
[0.5 1.  1.5]


In [ ]:
# np.sqrt  --> Computes the square root of each element in the array
np.sqrt([1,4,9])

array([1., 2., 3.])

In [ ]:
# np.exp --> Calculate the exponential of all elements in the input array.
np.exp([1,23,44,545,564])

array([2.71828183e+000, 9.74480345e+009, 1.28516001e+019, 4.90334710e+236,
       8.75160673e+244])

**Aggregate Functions**
* NumPy provides many functions for performing aggregate operations on arrays, such as sum, mean, max, min, etc.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Sum along columns:", np.sum(arr, axis=0))
print("Sum along rows:", np.sum(arr, axis=1))
print("Standard deviation:", np.std(arr))
print("Mean of all elements:", np.mean(arr))

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Sum along columns: [5 7 9]
Sum along rows: [ 6 15]
Standard deviation: 1.707825127659933
Mean of all elements: 3.5


# Broadcasting
* Broadcasting allows NumPy to perform operations on arrays of different shapes.
* If the arrays have the same shape, no broadcasting is necessary, and the operation is performed element-wise.
* If the arrays have different shapes, NumPy attempts to broadcast the smaller array's shape to match the larger array's shape.
* If the dimensions of the arrays are different, NumPy starts from the trailing dimensions and works backward, prepending 1s to the smaller shape until the shapes match.
* If the shapes still don't match after prepending 1s, NumPy raises a ValueError.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

# Broadcasting addition
print(a + b)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# Example Of Where Broadcasting is not possible
# Different shapes: (2, 3) and (3, 2)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

# INDEXING AND SLICING

**INDEXING**
* You can access elements of a NumPy array using indexing, similar to lists.

**Basic Indexing**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("First element:", arr[0])
print("Last element:", arr[-1])

First element: 1
Last element: 5


For multi-dimensional arrays, you need to specify a tuple of indices.

In [ ]:
Arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Arr[1, 2])
print(Arr[0][0])

6
1


**Fancy Indexing**
* Fancy indexing refers to the use of arrays of integers or boolean values to index another array. It allows for more complex and flexible selection and manipulation of array elements.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Use fancy indexing with integer arrays
indices = np.array([1, 3, 4])
selected_elements = arr[indices]

print(selected_elements)

[20 40 50]


In [ ]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

# Use fancy indexing to select specific rows and columns
rows = np.array([0, 1, 2])
cols = np.array([1, 0, 1])
selected_elements = arr_2d[rows, cols]

print(selected_elements)

[2 3 6]


**Boolean Indexing**
* Boolean indexing involves creating a boolean array that matches the shape of the original array. This boolean array is used to select elements from the original array where the boolean array is True.


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Create a boolean array
bool_arr = arr > 25

# Use boolean indexing
selected_elements = arr[bool_arr]

print(selected_elements)

[30 40 50]


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a boolean array
bool_arr_2d = arr_2d > 5

# Use boolean indexing
selected_elements = arr_2d[bool_arr_2d]

print(selected_elements)

[6 7 8 9]


**SLICING**
* Slicing allows you to access a range of elements in an array.

In [42]:
arr = np.array([1, 2, 3, 4, 5])

print("Elements from index 1 to 3:", arr[1:4])
print("Elements from the start to index 3:", arr[:4])
print("Elements from index 2 to the end:", arr[2:])
print("Every second element:", arr[::2])


Elements from index 1 to 3: [2 3 4]
Elements from the start to index 3: [1 2 3 4]
Elements from index 2 to the end: [3 4 5]
Every second element: [1 3 5]


**Multidimensional Array Slicing**
* For multidimensional arrays, you can specify a slice for each dimension, separated by commas.
* If you omit a dimension in the slicing, it selects all elements along that dimension.

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Slice of first two rows and columns:\n", arr[:2, :2])
print("Slice of last row:\n", arr[-1, :])
print("Slice of first two rows and columns:\n",arr[0:2, 0:2])

Slice of first two rows and columns:
 [[1 2]
 [4 5]]
Slice of last row:
 [7 8 9]
Slice of first two rows and columns:
 [[1 2]
 [4 5]]


In [47]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[1:10] = 10
print(a)

[ 1 10 10 10 10 10 10 10 10]
